### ISSUE TITLE
Integrate updated backgrounds

### ISSUE THREAD

**Issue by EchoFrost** [WatercressStudios/NaNoReNo2017#2]
Located in the [Our Home. Drive repository](https://drive.google.com/drive/folders/0B6-oks04JYM7NHJKT0VsVThBc1E)

It's probably worth communicating with Kenta to ensure we are updating things correctly :p 

Unsure if any new BGs were introduced with this set...

**Comment by sagittaeri** [comment]
Pull request with all current new BGs have been created. I may be expecting more new BGs from Kenta in the future, but for now we should merge in these current ones.
